CUDA_VISIBLE_DEVICES=1 python finetune.py \
  --base_model '/home/models/llama-7b-hf' \
  --data_path 'ft-training_set/math_1k.json' \
  --output_dir './final_trained_models/math_1k/lora_A' \
  --batch_size 4 \
  --micro_batch_size 4 \
  --num_epochs 3 \
  --num_epochs_coop 3 \
  --lora_r 8 \
  --learning_rate 3e-4 \
  --cutoff_len 256 \
  --val_set_size 10 \
  --adapter_name lora \
  --save_step 200 \
  --lora_alpha 64 \
  --target_modules '[q_proj,k_proj,v_proj]' \
  --expert_locations 'lora_A' \
