CUDA_VISIBLE_DEVICES=1 python finetune.py \
  --base_model '/home/models/llama-7b-hf' \
  --data_path 'ft-training_set/commonsense_170k.json' \
  --output_dir './final_trained_models/cs/llama/lora_A/3e-4' \
  --batch_size 16 \
  --micro_batch_size 16 \
  --num_epochs 3 \
  --num_epochs_coop 0 \
  --lora_r 32 \
  --learning_rate 3e-4 \
  --cutoff_len 256 \
  --val_set_size 120 \
  --adapter_name lora \
  --eval_step 10644 \
  --save_step 10644 \
  --lora_alpha 64 \
  --target_modules '[q_proj,k_proj,v_proj,gate_proj,up_proj,down_proj]' \
  --expert_locations 'lora_A' \
