CUDA_VISIBLE_DEVICES=5 python finetune.py \
  --base_model 'yahma/llama-7b-hf' \
  --data_path 'ft-training_set/math_10k.json' \
  --output_dir './final_trained_models/sparseft_3' \
  --batch_size 16 \
  --micro_batch_size 4 \
  --num_epochs 3 \
  --lora_r 32 \
  --use_sparseft True \
  --exp 0 \
  --budget 561000 \
  --learning_rate 1e-3 \
  --cutoff_len 256 \
  --val_set_size 120 \
  --adapter_name lora \
  --save_step 200 \
  --target_modules '[q_proj,v_proj,o_proj,k_proj,gate_proj,up_proj,down_proj]'